spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddlAuto: update

# 파일 업로드 경로
file:
  upload.path: D:/uploads/
  upload.url: /uploads/

# cors 설정
cors:
  allowed: https://pintech.koreait.xyz,https://localhost:3000 # next.js는 port를 3000번으로 할 거 같음.