server:
  port: 3997
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 나중에 바뀔것들.
              - 'http://localhost:3000'
              - 'https://pintech.koreait.xyz'

        allowCredentials: true # 요청시 인증정보 전송 허가
        allowedHeaders: '*'
        allowedMethods: '*'
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/** # 이쪽으로 api 요청 보내면 될거같음....
          filters:
            - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/** # 이쪽으로 api 요청 보내면 될거같음....
          filters:
            - RewritePath=/api/v1/file/?(?<path>.*),/$\{path}

#유레카 설정
eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway





















